version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/lambda"
    update_schedule: "weekly"
    default_reviewers:
      - yoshutch
    ignored_updates:
      - match:
          dependency_name: "aws-sdk"
          version_requirement: "2.x"
